# Generated by Django 4.0.4 on 2022-05-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('TodoId', models.AutoField(primary_key=True, serialize=False)),
                ('TodoTitle', models.CharField(max_length=100)),
                ('TodoDescription', models.CharField(max_length=200)),
                ('TodoStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
